spring.application.name=server
application.title=A visual novel store and builder! And made in Java21!

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://localhost:3306/fenixdb
spring.datasource.username=root
spring.datasource.password=Sandia4you
spring.jpa.show-sql=true